# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-16 09:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0005_remove_post_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='profile',
        ),
    ]
